title: Sean Dixon # your name (or website title) here
logo: "Headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst|Sports Data fanatic 
  <a href="https://www.linkedin.com/in/seantdixon1/">
  View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
